services:
  consul:
    image: consul:1.15.4
    hostname: localhost
    ports:
      - "8500:8500"
  haproxy:
    build:
      context: ../
      dockerfile: "docker/Haproxy-Dockerfile"
    ports:
      - "8080:8080"
    volumes:
      - ./generate-haproxy-config.sh:/usr/local/bin/generate-haproxy-config.sh
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - consul
      - app
      - second_app
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: ifmo
      POSTGRES_DB: ws
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  app:
    build:
      context: ../
      dockerfile: "docker/Dockerfile"
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - consul
      - db
  second_app:
    build:
      context: ../
      dockerfile: "docker/Dockerfile"
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    depends_on:
      - consul
      - db